// Sentinel Decision OS — Scenario Engine
// 3 demo scenarios with event timelines

export const SCENARIOS = {
    A: {
        id: 'A',
        name: 'Blueberry PHI Window Risk',
        nameZh: '蓝莓安全间隔期风险',
        description: 'High humidity triggers Botrytis during flowering, but harvest is imminent. Chemical spray is PHI-restricted, forcing biological control fallback.',
        field: 'BS-B3',
        crop: 'blueberry',
        startDay: 42,
        riskLevel: 'high',
        daysToHarvest: 4,
        initialState: {
            gradeClass: 'A',
            estimatedVolume: 3600,
        },
        events: [
            {
                step: 1,
                day: 42,
                title: 'Humidity Spike Detected',
                description: 'Relative humidity rises to 92%. Leaf wetness duration reaches 8 hours. Overcast for 3 consecutive days.',
                sensorOverrides: { humidity_pct: 92, leaf_wetness_hrs: 8.2, light_Lux: 4500, temp_C: 19.2, rainfall_mm: 3.5 },
                pestOverrides: { botrytis_spore_index: 72 },
                expectedAction: null,
            },
            {
                step: 2,
                day: 43,
                title: 'Botrytis Risk Critical',
                description: 'Spore index climbs to 85/100. System triggers risk assessment. Gray Mold score: 85 — ACTION REQUIRED.',
                sensorOverrides: { humidity_pct: 94, leaf_wetness_hrs: 9.5, light_Lux: 3200, temp_C: 18.5 },
                pestOverrides: { botrytis_spore_index: 85 },
                expectedAction: 'risk_trigger',
            },
            {
                step: 3,
                day: 43,
                title: 'Prescription Generated — PHI Constraint Fires',
                description: 'System generates fungicide Rx (Mancozeb). PHI check: requires 15d, only 4d to harvest. BLOCKED. System auto-falls back to biological control (Trichoderma).',
                sensorOverrides: { humidity_pct: 93, leaf_wetness_hrs: 8.8 },
                pestOverrides: { botrytis_spore_index: 85 },
                expectedAction: 'prescription_with_fallback',
            },
            {
                step: 4,
                day: 44,
                title: 'Biocontrol Execution',
                description: 'Trichoderma harzianum released in target zone. Ventilation increased. Execution fingerprint generated and matched.',
                sensorOverrides: { humidity_pct: 88, leaf_wetness_hrs: 6.5 },
                pestOverrides: { botrytis_spore_index: 75 },
                expectedAction: 'execution',
            },
            {
                step: 5,
                day: 46,
                title: '72h Verification — Risk Drops',
                description: 'Spore index drops to 42. Gray mold risk reduced from 85 to 42. Grade A protected. Revenue saved: 44,000 yuan.',
                sensorOverrides: { humidity_pct: 78, leaf_wetness_hrs: 3.2, light_Lux: 18000 },
                pestOverrides: { botrytis_spore_index: 42 },
                expectedAction: 'audit',
            },
        ],
        expectedOutcome: 'Grade A protected through biological control fallback. Revenue protected: ~44,000 yuan.',
    },

    B: {
        id: 'B',
        name: 'Fresh Cut Flower Gray Mold',
        nameZh: '鲜切花灰霉病',
        description: 'Monsoon-period humidity spike in greenhouse roses. Operator delay of 6 hours leads to partial damage and grade downgrade on 30% of stems.',
        field: 'YN-A2',
        crop: 'flower',
        startDay: 38,
        riskLevel: 'critical',
        daysToHarvest: 12,
        initialState: {
            gradeClass: 'A',
            estimatedVolume: 15000,
        },
        events: [
            {
                step: 1,
                day: 38,
                title: 'Monsoon Humidity Surge',
                description: 'Greenhouse humidity hits 94%. Leaf wetness at 10 hours. Gray mold conditions developing rapidly.',
                sensorOverrides: { humidity_pct: 94, leaf_wetness_hrs: 10, temp_C: 22.8, rainfall_mm: 8.5, wind_speed_ms: 0.3 },
                pestOverrides: { botrytis_spore_index: 78 },
                expectedAction: null,
            },
            {
                step: 2,
                day: 38,
                title: 'Risk Assessment — Gray Mold 88/100',
                description: 'System flags critical risk. Prescription generated: ventilation + Carbendazim spray. Decision window: 4 hours optimal.',
                sensorOverrides: { humidity_pct: 95, leaf_wetness_hrs: 11 },
                pestOverrides: { botrytis_spore_index: 88 },
                expectedAction: 'risk_trigger',
            },
            {
                step: 3,
                day: 39,
                title: 'Decision Delay — 6 Hours No Action',
                description: 'Operator does not execute prescription for 6 hours. System logs delay. Revenue impact calculated: 12,600 yuan at risk from timing loss.',
                sensorOverrides: { humidity_pct: 96, leaf_wetness_hrs: 12 },
                pestOverrides: { botrytis_spore_index: 92 },
                expectedAction: 'delay_logged',
                delayHours: 6,
            },
            {
                step: 4,
                day: 39,
                title: 'Delayed Execution',
                description: 'Prescription finally executed after 6h delay. Ventilation activated, Carbendazim applied. But gray mold has already spread to 30% of stems.',
                sensorOverrides: { humidity_pct: 85, leaf_wetness_hrs: 7 },
                pestOverrides: { botrytis_spore_index: 80 },
                expectedAction: 'execution_delayed',
            },
            {
                step: 5,
                day: 42,
                title: 'Partial Recovery — Grade Downgrade',
                description: 'Risk drops to 55 (partial effectiveness). 30% of stems downgraded from A to B. Revenue loss: 12,600 yuan. Audit: responsibility on operator-delay.',
                sensorOverrides: { humidity_pct: 76, leaf_wetness_hrs: 3, light_Lux: 16000 },
                pestOverrides: { botrytis_spore_index: 55 },
                expectedAction: 'audit_with_downgrade',
                gradeDowngrade: { from: 'A', to: 'B', affectedPct: 30 },
            },
        ],
        expectedOutcome: 'Grade B downgrade on 30% of stems due to 6h operator delay. Revenue loss: ~12,600 yuan.',
    },

    C: {
        id: 'C',
        name: 'Execution Deviation',
        nameZh: '执行偏差',
        description: 'Anthracnose prescription executed by drone, but dosage deviates to 1.2x. Fingerprint mismatch triggers audit, responsibility shifts to operator.',
        field: 'BS-B3',
        crop: 'blueberry',
        startDay: 35,
        riskLevel: 'elevated',
        daysToHarvest: 20,
        initialState: {
            gradeClass: 'A',
            estimatedVolume: 3600,
        },
        events: [
            {
                step: 1,
                day: 35,
                title: 'Anthracnose Detected',
                description: 'Warm humid conditions (26C, 82% RH). Fruit lesion rate rising. Risk assessment: Anthracnose 72/100.',
                sensorOverrides: { temp_C: 26.2, humidity_pct: 82, soil_moist_pct: 38 },
                pestOverrides: { botrytis_spore_index: 30 },
                expectedAction: null,
            },
            {
                step: 2,
                day: 36,
                title: 'Prescription Generated',
                description: 'System generates Rx: Chlorothalonil spot spray at 0.7x label rate. No constraint violations.',
                sensorOverrides: { temp_C: 27.1, humidity_pct: 84 },
                pestOverrides: {},
                expectedAction: 'prescription_normal',
            },
            {
                step: 3,
                day: 36,
                title: 'Drone Executes — Dosage Deviation',
                description: 'Drone applies 1.2x dosage instead of 0.7x. Execution fingerprint: MISMATCH. System flags deviation alert.',
                sensorOverrides: { temp_C: 26.5, humidity_pct: 80 },
                pestOverrides: {},
                expectedAction: 'execution_deviated',
                deviationFactor: 1.714, // 0.7 * 1.714 = ~1.2
            },
            {
                step: 4,
                day: 37,
                title: 'Deviation Audit',
                description: 'Audit: dosage 1.2x vs prescribed 0.7x (+71%). Still within label max (passes safety). But: extra cost 840 yuan, unnecessary soil residue. Responsibility: operator.',
                sensorOverrides: { temp_C: 25.8, humidity_pct: 76 },
                pestOverrides: { botrytis_spore_index: 22 },
                expectedAction: 'audit_deviation',
            },
            {
                step: 5,
                day: 39,
                title: 'Resolution — Compliance Pass',
                description: 'Risk reduced to 18. Grade A maintained. Compliance: all badges pass (dosage within label max). Economic note: 840 yuan excess cost, no grade impact.',
                sensorOverrides: { temp_C: 24.5, humidity_pct: 72, light_Lux: 22000 },
                pestOverrides: { botrytis_spore_index: 18 },
                expectedAction: 'resolved',
            },
        ],
        expectedOutcome: 'Fingerprint mismatch flagged. Responsibility shifted to operator. Grade A maintained but excess cost incurred.',
    },
};

export const getScenarioList = () => Object.values(SCENARIOS).map(s => ({
    id: s.id,
    name: s.name,
    nameZh: s.nameZh,
    description: s.description,
    field: s.field,
    crop: s.crop,
    riskLevel: s.riskLevel,
    eventCount: s.events.length,
    expectedOutcome: s.expectedOutcome,
}));
