// Sentinel Decision OS  - Scenario Engine v2
// 6 demo scenarios with rich event timelines, AI agent tracking, and outcome metrics

export const SCENARIOS = {
    A: {
        id: 'A',
        name: 'Blueberry PHI Window Risk',
        nameZh: '蓝莓 PHI 窗口风险',
        description: 'High humidity triggers Botrytis during flowering, but harvest is imminent. Chemical spray is PHI-restricted, forcing biological control fallback.',
        field: 'BS-B3',
        crop: 'blueberry',
        startDay: 42,
        riskLevel: 'high',
        daysToHarvest: 4,
        complexity: 4,
        threatType: 'disease',
        primaryThreat: 'Gray Mold (Botrytis)',
        initialState: {
            gradeClass: 'A',
            estimatedVolume: 3600,
        },
        outcomeMetrics: {
            gradeResult: 'A (protected)',
            revenueProtected: 44000,
            totalCost: 3200,
            chemicalReduction: '100%',
            responseTimeMin: 18,
            complianceScore: 100,
        },
        aiAgents: ['perception', 'analysis', 'decision', 'execution', 'audit'],
        prescriptionReport: {
            methods: [
                { name: 'Biocontrol Release', type: 'primary', description: 'Trichoderma harzianum spore release in target zone to compete with Botrytis', timing: 'Day 44, 06:00-08:00' },
                { name: 'Ventilation Increase', type: 'secondary', description: 'Increase exhaust fan output to 85% to lower humidity below 80% RH', timing: 'Day 44, continuous' },
                { name: 'Canopy Pruning', type: 'supporting', description: 'Remove infected leaves and improve air circulation in dense canopy zones', timing: 'Day 44, 09:00-11:00' },
            ],
            actors: [
                { id: 'ACT-A1', name: 'Field Team Alpha', role: 'Biocontrol Dispersal', zone: 'B3-East Rows 4-8', equipment: 'Trichoderma dispenser unit', status: 'assigned' },
                { id: 'ACT-A2', name: 'IoT Ventilation AI', role: 'Environment Control', zone: 'B3 Full Greenhouse', equipment: 'Automated exhaust system', status: 'assigned' },
                { id: 'ACT-A3', name: 'Pruning Crew B', role: 'Canopy Management', zone: 'B3-East Rows 1-8', equipment: 'Manual pruning tools + collection bags', status: 'assigned' },
            ],
            actions: [
                { step: 1, action: 'Activate ventilation to 85% output', actor: 'IoT Ventilation AI', priority: 'IMMEDIATE', status: 'pending' },
                { step: 2, action: 'Deploy Trichoderma harzianum in target rows', actor: 'Field Team Alpha', priority: 'HIGH', status: 'pending' },
                { step: 3, action: 'Prune infected leaves in dense canopy areas', actor: 'Pruning Crew B', priority: 'MEDIUM', status: 'pending' },
                { step: 4, action: 'Monitor humidity and spore index for 48h', actor: 'IoT Ventilation AI', priority: 'ONGOING', status: 'pending' },
                { step: 5, action: 'Drone verification scan at T+48h', actor: 'Drone-03', priority: 'SCHEDULED', status: 'pending' },
            ],
            chemicals: [
                { name: 'Trichoderma harzianum', type: 'Biocontrol Agent', dosage: '2x10鈦?CFU/g, 500g/ha', phi: 'N/A (biological)', safety: 'No PHI restriction' },
            ],
            timeline: '3-day treatment window (Day 44-46)',
            costBreakdown: [
                { item: 'Trichoderma harzianum (500g)', amount: 1800, note: 'Biocontrol agent x 2.8ha' },
                { item: 'Ventilation energy increase', amount: 350, note: 'Additional fan runtime 72h' },
                { item: 'Pruning labor (4h x 2 crew)', amount: 640, note: 'Manual canopy cleanup' },
                { item: 'Drone verification scan', amount: 410, note: 'Post-treatment survey flight' },
            ],
        },
        events: [
            {
                step: 1,
                day: 42,
                title: 'Humidity Spike Detected',
                description: 'Relative humidity rises to 92%. Leaf wetness duration reaches 8 hours. Overcast for 3 consecutive days.',
                sensorOverrides: { humidity_pct: 92, leaf_wetness_hrs: 8.2, light_Lux: 4500, temp_C: 19.2, rainfall_mm: 3.5 },
                pestOverrides: { botrytis_spore_index: 72 },
                expectedAction: null,
                aiAgentActions: [
                    { agent: 'perception', action: 'Detected humidity anomaly across 3 IoT nodes in B3-East zone' },
                    { agent: 'analysis', action: 'Cross-referenced weather API: 72h overcast forecast confirmed' },
                ],
            },
            {
                step: 2,
                day: 43,
                title: 'Botrytis Risk Critical',
                description: 'Spore index climbs to 85/100. System triggers risk assessment. Gray Mold score: 85  - ACTION REQUIRED.',
                sensorOverrides: { humidity_pct: 94, leaf_wetness_hrs: 9.5, light_Lux: 3200, temp_C: 18.5 },
                pestOverrides: { botrytis_spore_index: 85 },
                expectedAction: 'risk_trigger',
                aiAgentActions: [
                    { agent: 'analysis', action: 'LSTM temporal model detected accelerating spore count trend' },
                    { agent: 'decision', action: 'Risk score 85/100 exceeds critical threshold (70). Flagging for prescription.' },
                    { agent: 'perception', action: 'Dispatched Drone-03 for hyperspectral confirmation scan' },
                ],
            },
            {
                step: 3,
                day: 43,
                title: 'Prescription Generated  - PHI Constraint Fires',
                description: 'System generates fungicide Rx (Mancozeb). PHI check: requires 15d, only 4d to harvest. BLOCKED. System auto-falls back to biological control (Trichoderma).',
                sensorOverrides: { humidity_pct: 93, leaf_wetness_hrs: 8.8 },
                pestOverrides: { botrytis_spore_index: 85 },
                expectedAction: 'prescription_with_fallback',
                aiAgentActions: [
                    { agent: 'decision', action: 'Primary Rx (Mancozeb) blocked: PHI 15d > 4d remaining. Auto-selecting fallback.' },
                    { agent: 'decision', action: 'Fallback selected: Trichoderma harzianum  - biocontrol, no PHI restriction' },
                    { agent: 'audit', action: 'Pre-audit gate: PHI constraint documented, fallback reasoning recorded' },
                ],
                prescriptionData: {
                    primary: { chemical: 'Mancozeb 70% WP', blocked: true, reason: 'PHI 15d > 4d to harvest' },
                    fallback: { chemical: 'Trichoderma harzianum', method: 'Manual release + ventilation', cost: 3200 },
                },
            },
            {
                step: 4,
                day: 44,
                title: 'Biocontrol Execution',
                description: 'Trichoderma harzianum released in target zone. Ventilation increased to 85%. Execution fingerprint generated and matched.',
                sensorOverrides: { humidity_pct: 88, leaf_wetness_hrs: 6.5 },
                pestOverrides: { botrytis_spore_index: 75 },
                expectedAction: 'execution',
                aiAgentActions: [
                    { agent: 'execution', action: 'Multi-actor dispatch: Field Team (biocontrol) + IoT (ventilation 85%)' },
                    { agent: 'execution', action: 'Execution fingerprint generated: hash match [OK]' },
                    { agent: 'perception', action: 'Live monitoring: humidity dropping 1.2%/hr after ventilation increase' },
                ],
            },
            {
                step: 5,
                day: 45,
                title: '48h Progress Check',
                description: 'Spore index declining. Humidity stabilized at 82%. Trichoderma colonization confirmed by microscopy. Risk score: 58.',
                sensorOverrides: { humidity_pct: 82, leaf_wetness_hrs: 4.2, light_Lux: 12000 },
                pestOverrides: { botrytis_spore_index: 58 },
                expectedAction: null,
                aiAgentActions: [
                    { agent: 'perception', action: 'Drone-03 verification scan: lesion spread halted in rows 4-6' },
                    { agent: 'analysis', action: 'Treatment efficacy: 32% spore reduction in 48h  - on track' },
                ],
            },
            {
                step: 6,
                day: 46,
                title: '72h Verification  - Risk Drops',
                description: 'Spore index drops to 42. Gray mold risk reduced from 85 to 42. Grade A protected. Revenue saved: 44,000 yuan.',
                sensorOverrides: { humidity_pct: 78, leaf_wetness_hrs: 3.2, light_Lux: 18000 },
                pestOverrides: { botrytis_spore_index: 42 },
                expectedAction: 'audit',
                aiAgentActions: [
                    { agent: 'audit', action: 'Audit generated: Risk 85 -> 2, Grade A protected, CNY 44,000 revenue saved' },
                    { agent: 'audit', action: 'Responsibility: System (biocontrol fallback decision was correct)' },
                    { agent: 'analysis', action: 'ML feedback: 185 training points captured for model v4.3' },
                ],
            },
        ],
        expectedOutcome: 'Grade A protected through biological control fallback. Revenue protected: ~44,000 yuan.',
    },

    B: {
        id: 'B',
        name: 'Fresh Cut Flower Gray Mold',
        nameZh: '鲜切花灰霉病',
        description: 'Monsoon-period humidity spike in greenhouse roses. Operator delay of 6 hours leads to partial damage and grade downgrade on 30% of stems.',
        field: 'YN-A2',
        crop: 'flower',
        startDay: 38,
        riskLevel: 'critical',
        daysToHarvest: 12,
        complexity: 5,
        threatType: 'disease',
        primaryThreat: 'Gray Mold (Botrytis)',
        initialState: {
            gradeClass: 'A',
            estimatedVolume: 15000,
        },
        outcomeMetrics: {
            gradeResult: 'B (30% downgraded)',
            revenueProtected: 51000,
            revenueLost: 12600,
            totalCost: 4500,
            chemicalReduction: '45%',
            responseTimeMin: 380,
            complianceScore: 85,
        },
        aiAgents: ['perception', 'analysis', 'decision', 'execution', 'audit', 'watchdog'],
        prescriptionReport: {
            methods: [
                { name: 'Fungicide Spray', type: 'primary', description: 'Carbendazim 50% WP targeted spray on infected stems and surrounding buffer zone', timing: 'Day 39, ASAP (delayed 6h from optimal)' },
                { name: 'Emergency Ventilation', type: 'secondary', description: 'Activate all exhaust fans + dehumidifiers to rapidly lower humidity below 85%', timing: 'Day 39, immediate' },
                { name: 'Infected Stem Removal', type: 'supporting', description: 'Manual pruning of visibly infected stems (30% showing lesions)', timing: 'Day 39-40' },
            ],
            actors: [
                { id: 'ACT-B1', name: 'Drone-01 (DJI T40)', role: 'Fungicide Application', zone: 'A2-Main, A2-North', equipment: 'XR-110015VS nozzle, 40L tank', status: 'assigned' },
                { id: 'ACT-B2', name: 'Drone-02 (DJI T40)', role: 'Buffer Zone Spray', zone: 'A2-South buffer', equipment: 'XR-110015VS nozzle, 40L tank', status: 'assigned' },
                { id: 'ACT-B3', name: 'Pruning Crew A', role: 'Infected Stem Removal', zone: 'A2-Main Rows 1-12', equipment: 'Pruning shears, collection bags, PPE', status: 'assigned' },
                { id: 'ACT-B4', name: 'IoT Ventilation Tech', role: 'Environment Override', zone: 'A2 Full Greenhouse', equipment: 'Exhaust fans + 3x portable dehumidifiers', status: 'assigned' },
            ],
            actions: [
                { step: 1, action: 'Override ventilation to maximum output', actor: 'IoT Ventilation Tech', priority: 'IMMEDIATE', status: 'pending' },
                { step: 2, action: 'Deploy dehumidifiers in high-moisture zones', actor: 'IoT Ventilation Tech', priority: 'HIGH', status: 'pending' },
                { step: 3, action: 'Execute Carbendazim spray on main infection zones', actor: 'Drone-01', priority: 'HIGH', status: 'pending' },
                { step: 4, action: 'Spray buffer zone perimeter', actor: 'Drone-02', priority: 'HIGH', status: 'pending' },
                { step: 5, action: 'Remove visibly infected stems', actor: 'Pruning Crew A', priority: 'MEDIUM', status: 'pending' },
                { step: 6, action: 'Post-treatment monitoring (48h)', actor: 'All Actors', priority: 'ONGOING', status: 'pending' },
            ],
            chemicals: [
                { name: 'Carbendazim 50% WP (澶氳弻鐏?', type: 'Systemic Fungicide', dosage: '1000 ml/mu at 1:500 dilution', phi: '7 days', safety: 'PHI compliant (12d to harvest)' },
            ],
            timeline: '2-day treatment window (Day 39-40). NOTE: 6h delay from optimal window reduced efficacy to ~55%.',
            costBreakdown: [
                { item: 'Carbendazim 50% WP', amount: 1650, note: 'Fungicide x 5mu greenhouse' },
                { item: 'Drone operation (2x T40)', amount: 1400, note: '~90min flight time total' },
                { item: 'Pruning labor (6h x 3 crew)', amount: 960, note: 'Infected stem removal + disposal' },
                { item: 'Dehumidifier rental + energy', amount: 490, note: '3 units x 48h operation' },
            ],
        },
        events: [
            {
                step: 1,
                day: 38,
                title: 'Monsoon Humidity Surge',
                description: 'Greenhouse humidity hits 94%. Leaf wetness at 10 hours. Gray mold conditions developing rapidly.',
                sensorOverrides: { humidity_pct: 94, leaf_wetness_hrs: 10, temp_C: 22.8, rainfall_mm: 8.5, wind_speed_ms: 0.3 },
                pestOverrides: { botrytis_spore_index: 78 },
                expectedAction: null,
                aiAgentActions: [
                    { agent: 'perception', action: 'Monsoon weather pattern detected. All humidity sensors above 90%.' },
                    { agent: 'watchdog', action: 'Escalation: Greenhouse humidity critical for 3+ hours. Alert dispatched.' },
                ],
            },
            {
                step: 2,
                day: 38,
                title: 'Risk Assessment  - Gray Mold 88/100',
                description: 'System flags critical risk. Prescription generated: ventilation + Carbendazim spray. Decision window: 4 hours optimal.',
                sensorOverrides: { humidity_pct: 95, leaf_wetness_hrs: 11 },
                pestOverrides: { botrytis_spore_index: 88 },
                expectedAction: 'risk_trigger',
                aiAgentActions: [
                    { agent: 'analysis', action: 'Ensemble confidence 91%: Gray Mold score 88/100. All 3 models agree.' },
                    { agent: 'decision', action: 'CRITICAL: Risk >=70 - routed to human approval queue. Decision window: 4h.' },
                    { agent: 'watchdog', action: 'Timer started: human approval deadline T+4h before efficacy degrades' },
                ],
            },
            {
                step: 3,
                day: 39,
                title: 'Decision Delay  - 6 Hours No Action',
                description: 'Operator does not execute prescription for 6 hours. System logs delay. Revenue impact calculated: 12,600 yuan at risk from timing loss.',
                sensorOverrides: { humidity_pct: 96, leaf_wetness_hrs: 12 },
                pestOverrides: { botrytis_spore_index: 92 },
                expectedAction: 'delay_logged',
                delayHours: 6,
                aiAgentActions: [
                    { agent: 'watchdog', action: '[ALERT] 6h since prescription generated. No operator action. Spore index rising.' },
                    { agent: 'decision', action: 'Revenue impact recalculated: CNY 12,600 additional loss from delayed response' },
                    { agent: 'audit', action: 'Delay logged: T+6h beyond optimal window. Responsibility flag: operator.' },
                ],
            },
            {
                step: 4,
                day: 39,
                title: 'Delayed Execution',
                description: 'Prescription finally executed after 6h delay. Ventilation activated, Carbendazim applied. But gray mold has already spread to 30% of stems.',
                sensorOverrides: { humidity_pct: 85, leaf_wetness_hrs: 7 },
                pestOverrides: { botrytis_spore_index: 80 },
                expectedAction: 'execution_delayed',
                aiAgentActions: [
                    { agent: 'execution', action: 'Delayed execution detected: T+6h. Efficacy reduced to ~55% vs 85% at optimal timing.' },
                    { agent: 'execution', action: 'Actors dispatched: Drone-01 (Carbendazim spray) + IoT (dehumidifier + exhaust fan)' },
                    { agent: 'perception', action: 'Visual scan: 30% stem damage already visible. Grade B threshold reached.' },
                ],
            },
            {
                step: 5,
                day: 41,
                title: '48h Monitoring  - Partial Recovery',
                description: 'Gray mold spread contained but damage irreversible on 30% of stems. Humidity normalizing at 80%. Spore index declining.',
                sensorOverrides: { humidity_pct: 80, leaf_wetness_hrs: 4.5, light_Lux: 10000 },
                pestOverrides: { botrytis_spore_index: 65 },
                expectedAction: null,
                aiAgentActions: [
                    { agent: 'perception', action: 'Drone verification: infection spread halted. 30% damage confirmed irreversible.' },
                    { agent: 'analysis', action: 'Recovery trajectory: remaining 70% stems at Grade A quality' },
                ],
            },
            {
                step: 6,
                day: 42,
                title: 'Partial Recovery  - Grade Downgrade',
                description: 'Risk drops to 55 (partial effectiveness). 30% of stems downgraded from A to B. Revenue loss: 12,600 yuan. Audit: responsibility on operator-delay.',
                sensorOverrides: { humidity_pct: 76, leaf_wetness_hrs: 3, light_Lux: 16000 },
                pestOverrides: { botrytis_spore_index: 55 },
                expectedAction: 'audit_with_downgrade',
                gradeDowngrade: { from: 'A', to: 'B', affectedPct: 30 },
                aiAgentActions: [
                    { agent: 'audit', action: 'Audit: 30% stems downgraded Grade A->B. Loss: CNY 12,600. Cause: 6h operator delay.' },
                    { agent: 'audit', action: 'Responsibility: Operator (system prescribed within optimal window, execution delayed)' },
                    { agent: 'analysis', action: 'ML feedback: delay-impact data captured. Model calibrating response urgency weights.' },
                ],
            },
        ],
        expectedOutcome: 'Grade B downgrade on 30% of stems due to 6h operator delay. Revenue loss: ~12,600 yuan.',
    },

    C: {
        id: 'C',
        name: 'Execution Deviation',
        nameZh: '执行偏差',
        description: 'Anthracnose prescription executed by drone, but dosage deviates to 1.2x. Fingerprint mismatch triggers audit, responsibility shifts to operator.',
        field: 'BS-B3',
        crop: 'blueberry',
        startDay: 35,
        riskLevel: 'elevated',
        daysToHarvest: 20,
        complexity: 3,
        threatType: 'disease',
        primaryThreat: 'Anthracnose',
        initialState: {
            gradeClass: 'A',
            estimatedVolume: 3600,
        },
        outcomeMetrics: {
            gradeResult: 'A (maintained)',
            revenueProtected: 28000,
            totalCost: 3640,
            excessCost: 840,
            chemicalReduction: '30%',
            responseTimeMin: 22,
            complianceScore: 92,
        },
        aiAgents: ['perception', 'analysis', 'decision', 'execution', 'audit'],
        prescriptionReport: {
            methods: [
                { name: 'Precision Spot Spray', type: 'primary', description: 'Chlorothalonil 75% WG targeted at anthracnose lesion clusters identified by drone RGB scan', timing: 'Day 36, 05:30-07:30 (dawn window)' },
                { name: 'Soil Sampling', type: 'supporting', description: 'Post-spray soil residue monitoring at 3 grid points per treated zone', timing: 'Day 37' },
            ],
            actors: [
                { id: 'ACT-C1', name: 'DJI T40 Drone #1', role: 'Primary Spray', zone: 'B3-East Rows 2-6', equipment: 'T40 + XR nozzle, 0.7x dosage calibration', status: 'assigned' },
                { id: 'ACT-C2', name: 'DJI T40 Drone #2', role: 'Buffer Perimeter', zone: 'B3-East Rows 7-8 buffer', equipment: 'T40 + XR nozzle, 0.5x dosage calibration', status: 'assigned' },
                { id: 'ACT-C3', name: 'Ground Sensor Crew', role: 'Soil Monitoring', zone: 'B3-East 3-point grid', equipment: 'Portable soil residue meter', status: 'assigned' },
            ],
            actions: [
                { step: 1, action: 'Pre-flight calibration check (0.7x dosage verified)', actor: 'DJI T40 Drone #1', priority: 'HIGH', status: 'pending' },
                { step: 2, action: 'Execute spot spray on lesion clusters', actor: 'DJI T40 Drone #1', priority: 'HIGH', status: 'pending' },
                { step: 3, action: 'Buffer zone perimeter spray at 0.5x', actor: 'DJI T40 Drone #2', priority: 'MEDIUM', status: 'pending' },
                { step: 4, action: 'Collect soil samples at T+24h', actor: 'Ground Sensor Crew', priority: 'SCHEDULED', status: 'pending' },
            ],
            chemicals: [
                { name: 'Chlorothalonil 75% WG (百菌清', type: 'Contact Fungicide', dosage: '0.7x label rate (560 ml/mu)', phi: '14 days', safety: 'PHI compliant (20d to harvest)' },
            ],
            timeline: '1-day spray + 1-day soil monitoring',
            costBreakdown: [
                { item: 'Chlorothalonil 75% WG', amount: 1540, note: 'Fungicide x 2.8ha at 0.7x rate' },
                { item: 'Drone operation (2x T40)', amount: 1260, note: '~60min flight time' },
                { item: 'Soil sampling labor', amount: 480, note: '3-point grid sampling' },
                { item: 'Post-spray monitoring', amount: 360, note: 'Drone verification at T+48h' },
            ],
        },
        events: [
            {
                step: 1,
                day: 35,
                title: 'Anthracnose Detected',
                description: 'Warm humid conditions (26°C, 82% RH). Fruit lesion rate rising. Risk assessment: Anthracnose 72/100.',
                sensorOverrides: { temp_C: 26.2, humidity_pct: 82, soil_moist_pct: 38 },
                pestOverrides: { botrytis_spore_index: 30 },
                expectedAction: null,
                aiAgentActions: [
                    { agent: 'perception', action: 'Temperature-humidity envelope matches anthracnose infection window' },
                    { agent: 'analysis', action: 'Lesion detection via drone RGB: 12 fruit clusters showing early signs' },
                ],
            },
            {
                step: 2,
                day: 36,
                title: 'Prescription Generated',
                description: 'System generates Rx: Chlorothalonil spot spray at 0.7x label rate. No constraint violations.',
                sensorOverrides: { temp_C: 27.1, humidity_pct: 84 },
                pestOverrides: {},
                expectedAction: 'prescription_normal',
                aiAgentActions: [
                    { agent: 'decision', action: 'Rx generated: Chlorothalonil 0.7x spot spray. All 7 constraint checks passed.' },
                    { agent: 'decision', action: 'Auto-approved: Risk 72 >=70 but within auto-approval range for this threat type.' },
                ],
                prescriptionData: {
                    primary: { chemical: 'Chlorothalonil (百菌清', dosage: '0.7x', method: 'Drone spot spray' },
                },
            },
            {
                step: 3,
                day: 36,
                title: 'Drone Executes  - Dosage Deviation',
                description: 'Drone applies 1.2x dosage instead of 0.7x. Execution fingerprint: MISMATCH. System flags deviation alert.',
                sensorOverrides: { temp_C: 26.5, humidity_pct: 80 },
                pestOverrides: {},
                expectedAction: 'execution_deviated',
                deviationFactor: 1.714, // 0.7 * 1.714 = ~1.2
                aiAgentActions: [
                    { agent: 'execution', action: '[ALERT] FINGERPRINT MISMATCH: Dosage 1.2x vs prescribed 0.7x (+71% deviation)' },
                    { agent: 'execution', action: 'Deviation severity: WARNING. Within label max (passes safety) but exceeds prescribed.' },
                    { agent: 'watchdog', action: 'Deviation alert dispatched to operator. Audit trail updated.' },
                ],
            },
            {
                step: 4,
                day: 37,
                title: 'Deviation Audit',
                description: 'Audit: dosage 1.2x vs prescribed 0.7x (+71%). Still within label max (passes safety). But: extra cost 840 yuan, unnecessary soil residue. Responsibility: operator.',
                sensorOverrides: { temp_C: 25.8, humidity_pct: 76 },
                pestOverrides: { botrytis_spore_index: 22 },
                expectedAction: 'audit_deviation',
                aiAgentActions: [
                    { agent: 'audit', action: 'Deviation audit: +71% dosage. Within label max  - no safety violation.' },
                    { agent: 'audit', action: 'Economic impact: +CNY 840 excess cost. Environmental: elevated soil residue.' },
                    { agent: 'audit', action: 'Responsibility assignment: Operator (system prescribed correctly, execution deviated)' },
                ],
            },
            {
                step: 5,
                day: 38,
                title: '48h Effect Check',
                description: 'Anthracnose lesions declining. The higher dosage was effective but unnecessary. Risk score: 25.',
                sensorOverrides: { temp_C: 25.0, humidity_pct: 74, light_Lux: 20000 },
                pestOverrides: { botrytis_spore_index: 20 },
                expectedAction: null,
                aiAgentActions: [
                    { agent: 'analysis', action: 'Treatment effective: lesion count 12 -> . Higher dosage accelerated but was unnecessary.' },
                    { agent: 'perception', action: 'Drone scan confirms: no new lesion formation in treated zones' },
                ],
            },
            {
                step: 6,
                day: 39,
                title: 'Resolution  - Compliance Pass',
                description: 'Risk reduced to 18. Grade A maintained. Compliance: all badges pass (dosage within label max). Economic note: 840 yuan excess cost, no grade impact.',
                sensorOverrides: { temp_C: 24.5, humidity_pct: 72, light_Lux: 22000 },
                pestOverrides: { botrytis_spore_index: 18 },
                expectedAction: 'resolved',
                aiAgentActions: [
                    { agent: 'audit', action: 'Final audit: Grade A maintained. CNY 28,000 revenue protected. Excess cost: CNY 840.' },
                    { agent: 'analysis', action: 'ML feedback: deviation-impact data added to calibration set (n=186)' },
                ],
            },
        ],
        expectedOutcome: 'Fingerprint mismatch flagged. Responsibility shifted to operator. Grade A maintained but excess cost incurred.',
    },

    D: {
        id: 'D',
        name: 'Multi-Pest Cascade',
        nameZh: '多虫害级联风险',
        description: 'Aphid outbreak weakens plant immunity, triggering secondary Botrytis infection. Requires sequential compound treatment: biocontrol for aphids, then targeted fungicide.',
        field: 'BS-B3',
        crop: 'blueberry',
        startDay: 30,
        riskLevel: 'critical',
        daysToHarvest: 25,
        complexity: 5,
        threatType: 'compound',
        primaryThreat: 'Aphids  -> Botrytis Cascade',
        initialState: {
            gradeClass: 'A',
            estimatedVolume: 3600,
        },
        outcomeMetrics: {
            gradeResult: 'A (protected)',
            revenueProtected: 68000,
            totalCost: 5800,
            chemicalReduction: '55%',
            responseTimeMin: 35,
            complianceScore: 98,
        },
        aiAgents: ['perception', 'analysis', 'decision', 'execution', 'audit', 'watchdog'],
        prescriptionReport: {
            methods: [
                { name: 'Phase 1: Biocontrol + Insecticide', type: 'primary', description: 'Ladybug release (5000 units) + Imidacloprid 0.8x targeted spray on aphid hotspot rows', timing: 'Day 31-33' },
                { name: 'Phase 2: Preventive Fungicide', type: 'secondary', description: 'Mancozeb 0.5x precision spray on aphid-damaged tissue to prevent secondary Botrytis', timing: 'Day 34+ (after Phase 1 verified)' },
                { name: 'IPM Monitoring', type: 'supporting', description: 'Continuous sticky trap monitoring + drone scans to verify aphid decline and watch for fungal entry', timing: 'Day 31-38 (throughout)' },
            ],
            actors: [
                { id: 'ACT-D1', name: 'Field Team B', role: 'Ladybug Release', zone: 'B3-East Rows 2,5,7', equipment: 'Biocontrol dispersal containers (5000 Coccinellidae)', status: 'assigned' },
                { id: 'ACT-D2', name: 'DJI T40 Drone #1', role: 'Insecticide Spray (Phase 1)', zone: 'B3-East Rows 2,5,7 hotspots', equipment: 'T40 + insecticide nozzle, Imidacloprid 0.8x', status: 'assigned' },
                { id: 'ACT-D3', name: 'Scout Drone #3', role: 'RGB + Multispectral Monitoring', zone: 'B3-East Full Coverage', equipment: 'DJI Mavic 3M (multispectral)', status: 'assigned' },
                { id: 'ACT-D4', name: 'Soil Sampling Team', role: 'Residue Monitoring', zone: 'B3-East 5-point grid', equipment: 'Portable soil analysis kit', status: 'assigned' },
                { id: 'ACT-D5', name: 'DJI T40 Drone #2', role: 'Fungicide Spray (Phase 2)', zone: 'B3 aphid-damaged zones only', equipment: 'T40 + fungicide nozzle, Mancozeb 0.5x', status: 'standby' },
            ],
            actions: [
                { step: 1, action: 'Release 5000 ladybugs in aphid hotspot rows', actor: 'Field Team B', priority: 'HIGH', status: 'pending' },
                { step: 2, action: 'Execute Imidacloprid 0.8x targeted spray on rows 2,5,7', actor: 'DJI T40 Drone #1', priority: 'HIGH', status: 'pending' },
                { step: 3, action: 'Continuous aerial monitoring every 12h', actor: 'Scout Drone #3', priority: 'ONGOING', status: 'pending' },
                { step: 4, action: 'Verify Phase 1 efficacy (aphids < 5/leaf)', actor: 'Scout Drone #3', priority: 'GATE', status: 'pending' },
                { step: 5, action: 'Execute Mancozeb 0.5x on damaged tissue zones', actor: 'DJI T40 Drone #2', priority: 'HIGH', status: 'pending' },
                { step: 6, action: 'Soil residue sampling at T+72h', actor: 'Soil Sampling Team', priority: 'SCHEDULED', status: 'pending' },
                { step: 7, action: 'Final verification scan + audit', actor: 'Scout Drone #3', priority: 'SCHEDULED', status: 'pending' },
            ],
            chemicals: [
                { name: 'Imidacloprid 20% SL (鍚¤櫕鍟?', type: 'Systemic Insecticide', dosage: '0.8x label rate', phi: '14 days', safety: 'PHI compliant (25d to harvest)' },
                { name: 'Mancozeb 70% WP (代森锰锌)', type: 'Contact Fungicide', dosage: '0.5x label rate (preventive)', phi: '15 days', safety: 'PHI compliant (25d to harvest)' },
                { name: 'Coccinellidae (Ladybugs)', type: 'Biocontrol Agent', dosage: '5000 units per release', phi: 'N/A', safety: 'No restriction' },
            ],
            timeline: '8-day compound treatment (Day 31-38). Phase 1: 3 days. Gate check: Day 34. Phase 2: 2 days.',
            costBreakdown: [
                { item: 'Ladybugs (5000 Coccinellidae)', amount: 850, note: 'Biocontrol release' },
                { item: 'Imidacloprid 20% SL', amount: 1200, note: 'Insecticide for Phase 1' },
                { item: 'Mancozeb 70% WP', amount: 680, note: 'Preventive fungicide Phase 2' },
                { item: 'Drone operations (3x drones)', amount: 1950, note: 'Spray + monitoring flights' },
                { item: 'Soil sampling + analysis', amount: 520, note: '5-point grid residue test' },
                { item: 'Field labor (biocontrol)', amount: 600, note: 'Ladybug release + monitoring' },
            ],
        },
        events: [
            {
                step: 1,
                day: 30,
                title: 'Aphid Population Surge',
                description: 'Sticky trap counts triple overnight: 45/day (threshold: 30). Aphids per leaf: 8 (threshold: 5). Warm spell accelerating reproduction.',
                sensorOverrides: { temp_C: 24.5, humidity_pct: 72, wind_speed_ms: 1.2, light_Lux: 22000 },
                pestOverrides: { aphids_per_leaf: 8, sticky_trap_whitefly: 45, botrytis_spore_index: 20 },
                expectedAction: null,
                aiAgentActions: [
                    { agent: 'perception', action: 'Pest trap camera AI: aphid count 8/leaf, 3x above threshold across 5 trap stations' },
                    { agent: 'analysis', action: 'Population model: doubling time 3.2 days at current temperature. Outbreak trajectory.' },
                    { agent: 'watchdog', action: 'Cascade risk flagged: aphid damage weakens plant cuticle  -> fungal entry pathway' },
                ],
            },
            {
                step: 2,
                day: 31,
                title: 'Compound Risk Assessment',
                description: 'AI identifies cascade risk: Aphids at 65/100 PLUS predicted secondary Botrytis at 45/100 (rising). Compound threat score: 78/100.',
                sensorOverrides: { temp_C: 25.2, humidity_pct: 75, leaf_wetness_hrs: 3.5 },
                pestOverrides: { aphids_per_leaf: 11, sticky_trap_whitefly: 52, botrytis_spore_index: 35 },
                expectedAction: 'risk_trigger',
                aiAgentActions: [
                    { agent: 'analysis', action: 'CASCADE DETECTION: Aphid feeding damage  -> weakened cuticle  -> Botrytis entry probability +42%' },
                    { agent: 'analysis', action: 'Historical match: 89% of aphid outbreaks at this severity led to secondary fungal within 5-8 days' },
                    { agent: 'decision', action: 'Compound risk score 78/100. Sequential treatment plan required. Route to approval.' },
                ],
            },
            {
                step: 3,
                day: 31,
                title: 'Sequential Prescription  - Phase 1: Biocontrol',
                description: 'System generates compound Rx: Phase 1 (Day 31-33): Ladybug release + Imidacloprid targeted spray on hotspot rows. Phase 2 (Day 34+): Preventive fungicide after aphid control.',
                sensorOverrides: { temp_C: 25.0, humidity_pct: 76 },
                pestOverrides: { aphids_per_leaf: 12, botrytis_spore_index: 38 },
                expectedAction: 'prescription_normal',
                aiAgentActions: [
                    { agent: 'decision', action: 'Compound Rx: Phase 1  - Ladybug release (5000 units) + Imidacloprid 0.8x on rows 2,5,7' },
                    { agent: 'decision', action: 'Phase 2 scheduled: Mancozeb 0.5x preventive spray after aphid control confirmed (Day 34+)' },
                    { agent: 'audit', action: 'Pre-audit: both chemicals PHI-compliant (25d to harvest), no MOA conflict' },
                ],
                prescriptionData: {
                    phase1: { chemical: 'Ladybug Release + Imidacloprid 0.8x', target: 'Aphids', timeline: 'Day 31-33' },
                    phase2: { chemical: 'Mancozeb 0.5x preventive', target: 'Botrytis prevention', timeline: 'Day 34+' },
                },
            },
            {
                step: 4,
                day: 32,
                title: 'Phase 1 Execution  - Biocontrol + Insecticide',
                description: 'Ladybugs released in rows 2,5,7. Drone applies Imidacloprid to aphid hotspots. IoT ventilation increased. Multi-actor coordination.',
                sensorOverrides: { temp_C: 24.8, humidity_pct: 74, wind_speed_ms: 1.5 },
                pestOverrides: { aphids_per_leaf: 10, botrytis_spore_index: 40 },
                expectedAction: 'execution',
                aiAgentActions: [
                    { agent: 'execution', action: 'Phase 1 dispatch: Field Team B  -> ladybug release | Drone-01  -> Imidacloprid rows 2,5,7' },
                    { agent: 'execution', action: 'Execution fingerprint generated: all parameters match [OK]' },
                    { agent: 'perception', action: 'Live monitoring: aphid activity declining in treated rows within 4 hours' },
                ],
            },
            {
                step: 5,
                day: 34,
                title: 'Phase 1 Verified  - Aphid Control Confirmed',
                description: 'Aphids reduced to 3/leaf (below threshold). Ladybug population establishing. Botrytis risk held at 42  - Phase 2 fungicide authorized.',
                sensorOverrides: { temp_C: 23.5, humidity_pct: 78, leaf_wetness_hrs: 4.0 },
                pestOverrides: { aphids_per_leaf: 3, sticky_trap_whitefly: 18, botrytis_spore_index: 42 },
                expectedAction: 'prescription_normal',
                aiAgentActions: [
                    { agent: 'perception', action: 'Drone scan: aphid count 3/leaf (down from 12). Biocontrol established.' },
                    { agent: 'analysis', action: 'Phase 1 efficacy: 75% reduction in 48h. Phase 2 conditions met.' },
                    { agent: 'decision', action: 'Phase 2 authorized: Mancozeb 0.5x preventive spray. Aphid-weakened tissue targeted.' },
                ],
            },
            {
                step: 6,
                day: 35,
                title: 'Phase 2 Execution  - Preventive Fungicide',
                description: 'Mancozeb 0.5x applied to aphid-damaged zones. Precision targeting of weakened tissue only. 65% chemical reduction vs blanket spray.',
                sensorOverrides: { temp_C: 23.0, humidity_pct: 76, wind_speed_ms: 1.0 },
                pestOverrides: { aphids_per_leaf: 2, botrytis_spore_index: 38 },
                expectedAction: 'execution',
                aiAgentActions: [
                    { agent: 'execution', action: 'Phase 2: Drone-01 precision spray, targeting aphid-damaged canopy segments only' },
                    { agent: 'execution', action: 'Chemical savings: 65% reduction vs broadcast (damaged zones only = 35% of field)' },
                ],
            },
            {
                step: 7,
                day: 38,
                title: 'Full Resolution  - Cascade Prevented',
                description: 'Both threats neutralized. Aphids at 1/leaf. Botrytis risk dropped to 22. No secondary infection materialized. Grade A protected. Revenue saved: CNY 68,000.',
                sensorOverrides: { temp_C: 22.5, humidity_pct: 73, leaf_wetness_hrs: 2.5, light_Lux: 20000 },
                pestOverrides: { aphids_per_leaf: 1, sticky_trap_whitefly: 10, botrytis_spore_index: 22 },
                expectedAction: 'audit',
                aiAgentActions: [
                    { agent: 'audit', action: 'Compound audit: Aphid 65->1, Botrytis 45->22. Cascade prevented. CNY 68,000 protected.' },
                    { agent: 'audit', action: 'Sequential treatment validated: 2-phase approach saved 55% chemical vs single broadcast' },
                    { agent: 'analysis', action: 'ML feedback: cascade prediction model accuracy confirmed. 210 training points captured.' },
                ],
            },
        ],
        expectedOutcome: 'Cascade prevented through sequential compound treatment. Grade A protected. Revenue: ~68,000 yuan. Chemical reduction: 55%.',
    },

    E: {
        id: 'E',
        name: 'Frost Emergency Response',
        nameZh: '霜冻应急响应',
        description: 'Sudden cold front drops temperature to 2°C during flowering. Emergency non-chemical response: irrigation frost protection, heated air blowers, and thermal blankets.',
        field: 'BS-B3',
        crop: 'blueberry',
        startDay: 25,
        riskLevel: 'high',
        daysToHarvest: 35,
        complexity: 4,
        threatType: 'environmental',
        primaryThreat: 'Frost Damage',
        initialState: {
            gradeClass: 'A',
            estimatedVolume: 3600,
        },
        outcomeMetrics: {
            gradeResult: 'A (protected)',
            revenueProtected: 52000,
            totalCost: 1800,
            chemicalReduction: '100%',
            responseTimeMin: 8,
            complianceScore: 100,
        },
        aiAgents: ['perception', 'analysis', 'decision', 'execution', 'watchdog'],
        prescriptionReport: {
            methods: [
                { name: 'Overhead Irrigation Protection', type: 'primary', description: 'Activate overhead sprinklers to create ice film layer  - releases latent heat at 0°C to protect flowers', timing: 'Day 27, 03:00 (pre-frost activation)' },
                { name: 'Heated Air Blowers', type: 'secondary', description: 'Deploy 4x propane-powered air blowers at field perimeter to circulate warm air through canopy', timing: 'Day 27, 03:00-08:00' },
                { name: 'Thermal Blanket Deployment', type: 'supporting', description: 'Cover most vulnerable rows (1-3, early-bloom) with reflective thermal blankets', timing: 'Day 26 evening, pre-positioned' },
            ],
            actors: [
                { id: 'ACT-E1', name: 'Irrigation Control System', role: 'Frost Protection Spray', zone: 'B3 Full Field Overhead', equipment: 'Overhead sprinkler array (12L/min)', status: 'assigned' },
                { id: 'ACT-E2', name: 'Heater Array (4 units)', role: 'Warm Air Circulation', zone: 'B3 Perimeter (N, S, E, W)', equipment: '4x propane blower heaters (50kW each)', status: 'assigned' },
                { id: 'ACT-E3', name: 'Blanket Deployment Crew', role: 'Physical Protection', zone: 'B3 Rows 1-3 (vulnerable)', equipment: 'Reflective thermal blankets (50m2x6)', status: 'assigned' },
                { id: 'ACT-E4', name: 'Monitoring Drone', role: 'Thermal Verification', zone: 'B3 Full Field', equipment: 'DJI M30T (thermal camera)', status: 'assigned' },
            ],
            actions: [
                { step: 1, action: 'Pre-position thermal blankets on rows 1-3', actor: 'Blanket Deployment Crew', priority: 'HIGH', status: 'pending' },
                { step: 2, action: 'Power up heater array and verify fuel levels', actor: 'Heater Array', priority: 'HIGH', status: 'pending' },
                { step: 3, action: 'Activate overhead irrigation at T-frost threshold (5°C)', actor: 'Irrigation Control System', priority: 'IMMEDIATE', status: 'pending' },
                { step: 4, action: 'Activate all heaters at T-frost threshold', actor: 'Heater Array', priority: 'IMMEDIATE', status: 'pending' },
                { step: 5, action: 'Deploy thermal drone for canopy temperature monitoring', actor: 'Monitoring Drone', priority: 'ONGOING', status: 'pending' },
                { step: 6, action: 'Stand-down after temperature > 8°C sustained for 1h', actor: 'All Actors', priority: 'CONDITIONAL', status: 'pending' },
            ],
            chemicals: [
                { name: 'None', type: 'Non-Chemical Intervention', dosage: 'N/A', phi: 'N/A', safety: 'Zero chemical usage  - 100% physical protection' },
            ],
            timeline: '24h emergency window (Day 26 evening  -> Day 27 morning). Pre-positioning: 6h before frost.',
            costBreakdown: [
                { item: 'Propane fuel (4 heaters x 5h)', amount: 680, note: 'Frost night fuel consumption' },
                { item: 'Irrigation water + pump energy', amount: 320, note: 'Overnight sprinkler operation' },
                { item: 'Thermal blanket crew labor', amount: 480, note: 'Evening deploy + morning stow' },
                { item: 'Thermal drone flight', amount: 320, note: 'M30T 4h continuous monitoring' },
            ],
        },
        events: [
            {
                step: 1,
                day: 25,
                title: 'Cold Front Warning  - 48h Advance',
                description: 'Weather API predicts Siberian cold front arrival in 48h. Min temp forecast: 2°C at 05:00 Day 27. Current flowering stage is highly frost-sensitive.',
                sensorOverrides: { temp_C: 15.2, humidity_pct: 65, wind_speed_ms: 3.5, light_Lux: 18000 },
                pestOverrides: { botrytis_spore_index: 15 },
                expectedAction: null,
                aiAgentActions: [
                    { agent: 'perception', action: 'Weather API alert: Siberian cold front ETA 48h. Min forecast 2°C (threshold: 5°C)' },
                    { agent: 'analysis', action: 'Frost risk model: 94% probability of sub-3°C for 4+ hours during flowering stage' },
                    { agent: 'watchdog', action: 'PROACTIVE ALERT: Frost risk HIGH. Pre-emptive planning recommended.' },
                ],
            },
            {
                step: 2,
                day: 26,
                title: 'Temperature Dropping  - Preparation Phase',
                description: 'Temperature falling at -0.8°C/hr. Current 8°C at sunset. AI pre-positions assets: heaters checked, irrigation system pressurized, thermal blankets staged.',
                sensorOverrides: { temp_C: 8.0, humidity_pct: 55, wind_speed_ms: 4.2, light_Lux: 3000 },
                pestOverrides: { botrytis_spore_index: 12 },
                expectedAction: 'risk_trigger',
                aiAgentActions: [
                    { agent: 'analysis', action: 'Cooling rate -0.8°C/hr. Frost threshold (5°C) ETA: 3.5 hours.' },
                    { agent: 'decision', action: 'Emergency Rx: 3-layer frost protection plan generated. No chemicals needed.' },
                    { agent: 'execution', action: 'Pre-positioning: heated air blowers powered up, irrigation system pressurized, blanket crew alerted' },
                ],
            },
            {
                step: 3,
                day: 26,
                title: 'Emergency Prescription  - Frost Protection',
                description: 'Non-chemical emergency plan: (1) Overhead irrigation frost protection, (2) Heated air blowers at field perimeter, (3) Thermal blankets on most vulnerable rows.',
                sensorOverrides: { temp_C: 5.5, humidity_pct: 52, wind_speed_ms: 3.0 },
                pestOverrides: {},
                expectedAction: 'prescription_normal',
                aiAgentActions: [
                    { agent: 'decision', action: 'Frost Rx: Layer 1  - irrigation film (latent heat), Layer 2  - blowers, Layer 3  - blankets' },
                    { agent: 'decision', action: 'Auto-approved: non-chemical, no PHI/wind constraints. Emergency protocol activated.' },
                    { agent: 'audit', action: 'Pre-audit: zero chemical usage. Environmental impact: positive (water recycled via drainage)' },
                ],
                prescriptionData: {
                    primary: { method: 'Overhead Irrigation + Heat + Blankets', chemical: 'None (Non-chemical)', cost: 1800 },
                },
            },
            {
                step: 4,
                day: 27,
                title: 'Frost Night Execution',
                description: 'Temperature hits 2.1°C at 04:30. All 3 protection layers active. Irrigation creates ice film (releases latent heat at 0°C). Blowers circulate warm air. Blankets on rows 1-3.',
                sensorOverrides: { temp_C: 2.1, humidity_pct: 48, wind_speed_ms: 2.0, light_Lux: 0 },
                pestOverrides: {},
                expectedAction: 'execution',
                aiAgentActions: [
                    { agent: 'execution', action: 'FROST NIGHT: Irrigation pump ON (12L/min), 4x blowers active, blankets deployed rows 1-3' },
                    { agent: 'perception', action: 'Canopy temp sensors: 3.8°C under protection vs 2.1°C ambient. Protection effective.' },
                    { agent: 'watchdog', action: 'Continuous monitoring: sensor readings every 60 seconds. All actors reporting nominal.' },
                ],
            },
            {
                step: 5,
                day: 27,
                title: 'Temperature Recovery  - Dawn',
                description: 'Sunrise at 07:15. Temperature recovering: 5.8°C and rising. Protection maintained until 8°C confirmed. Zero frost damage observed.',
                sensorOverrides: { temp_C: 5.8, humidity_pct: 62, wind_speed_ms: 1.5, light_Lux: 8000 },
                pestOverrides: {},
                expectedAction: null,
                aiAgentActions: [
                    { agent: 'perception', action: 'Temperature recovery confirmed: 5.8°C at 08:00, rising at +1.2°C/hr' },
                    { agent: 'execution', action: 'Protection stand-down: blowers  -> idle, irrigation  -> normal, blankets  -> stow at 10°C' },
                    { agent: 'analysis', action: 'Canopy inspection: zero ice damage, zero frost burn on 100% of sampled flowers' },
                ],
            },
            {
                step: 6,
                day: 28,
                title: 'Post-Frost Verification  - Zero Damage',
                description: 'Full drone inspection confirms zero frost damage. All flowers intact. Canopy health NDVI unchanged. Grade A protected. Revenue saved: CNY 52,000.',
                sensorOverrides: { temp_C: 16.5, humidity_pct: 68, wind_speed_ms: 1.0, light_Lux: 20000 },
                pestOverrides: { botrytis_spore_index: 10 },
                expectedAction: 'audit',
                aiAgentActions: [
                    { agent: 'audit', action: 'Frost audit: zero damage, zero chemicals, CNY 1,800 cost, CNY 52,000 revenue protected' },
                    { agent: 'audit', action: 'ROI: 28.9x. Best single-intervention ROI this season.' },
                    { agent: 'analysis', action: 'ML feedback: frost protection threshold model validated. 95 training points captured.' },
                ],
            },
        ],
        expectedOutcome: 'Zero frost damage through 3-layer non-chemical protection. Grade A protected. Revenue: ~52,000 yuan. ROI: 28.9x.',
    },

    F: {
        id: 'F',
        name: 'Greenhouse Ventilation Failure',
        nameZh: '温室通风故障',
        description: 'IoT ventilation system fails during a heat spike in the rose greenhouse. Manual override required. Emergency spray to prevent rapid Botrytis outbreak while repairs proceed.',
        field: 'YN-A2',
        crop: 'flower',
        startDay: 45,
        riskLevel: 'critical',
        daysToHarvest: 8,
        complexity: 5,
        threatType: 'system_failure',
        primaryThreat: 'IoT System Failure + Botrytis',
        initialState: {
            gradeClass: 'A',
            estimatedVolume: 15000,
        },
        outcomeMetrics: {
            gradeResult: 'A (recovered)',
            revenueProtected: 72000,
            totalCost: 6200,
            chemicalReduction: '40%',
            responseTimeMin: 12,
            complianceScore: 95,
        },
        aiAgents: ['perception', 'analysis', 'decision', 'execution', 'audit', 'watchdog'],
        prescriptionReport: {
            methods: [
                { name: 'Manual Ventilation Override', type: 'primary', description: 'Open all greenhouse doors and windows manually to restore airflow while HVAC system is offline', timing: 'Day 45, IMMEDIATE' },
                { name: 'Emergency Fungicide Spray', type: 'secondary', description: 'Carbendazim 50% WP emergency application to prevent Botrytis outbreak in high-humidity conditions', timing: 'Day 45, within 2h of ventilation' },
                { name: 'Dehumidifier Deployment', type: 'supporting', description: 'Deploy 3x portable industrial dehumidifiers in highest-humidity zones', timing: 'Day 45, immediate' },
                { name: 'HVAC Repair', type: 'infrastructure', description: 'Dispatch maintenance team to diagnose and replace failed exhaust fan motor', timing: 'Day 45-46' },
            ],
            actors: [
                { id: 'ACT-F1', name: 'Field Team Alpha', role: 'Manual Door/Window Override', zone: 'A2 Full Greenhouse', equipment: 'Manual override tools', status: 'assigned' },
                { id: 'ACT-F2', name: 'Facility Team', role: 'Dehumidifier Deployment', zone: 'A2-Main, A2-North (high humidity)', equipment: '3x Industrial dehumidifiers (20L/day)', status: 'assigned' },
                { id: 'ACT-F3', name: 'Drone-01 (DJI T40)', role: 'Emergency Fungicide Spray', zone: 'A2-Main, A2-North high-risk zones', equipment: 'T40 + emergency spray nozzle', status: 'assigned' },
                { id: 'ACT-F4', name: 'HVAC Maintenance Crew', role: 'Fan Motor Repair', zone: 'A2 mechanical room', equipment: 'Replacement motor + electrical tools', status: 'dispatched' },
            ],
            actions: [
                { step: 1, action: 'Open all greenhouse doors and vents (manual)', actor: 'Field Team Alpha', priority: 'IMMEDIATE', status: 'pending' },
                { step: 2, action: 'Deploy portable dehumidifiers in hot spots', actor: 'Facility Team', priority: 'IMMEDIATE', status: 'pending' },
                { step: 3, action: 'Execute Carbendazim emergency spray on high-risk zones', actor: 'Drone-01', priority: 'HIGH', status: 'pending' },
                { step: 4, action: 'Diagnose HVAC failure and begin motor replacement', actor: 'HVAC Maintenance Crew', priority: 'HIGH', status: 'pending' },
                { step: 5, action: 'Continuous humidity monitoring (every 10 min)', actor: 'IoT Sensors (backup)', priority: 'ONGOING', status: 'pending' },
                { step: 6, action: 'Post-repair system verification + dehumidifier removal', actor: 'Facility Team', priority: 'SCHEDULED', status: 'pending' },
            ],
            chemicals: [
                { name: 'Carbendazim 50% WP (澶氳弻鐏?', type: 'Systemic Fungicide (Emergency)', dosage: '1200 ml/mu at 1:400 dilution', phi: '7 days', safety: 'PHI compliant (8d to harvest  - tight margin)' },
            ],
            timeline: '2-day emergency response (Day 45-46). Ventilation restored Day 46 AM.',
            costBreakdown: [
                { item: 'Carbendazim 50% WP (emergency)', amount: 2100, note: 'Higher dosage for emergency' },
                { item: 'Drone emergency spray operation', amount: 1400, note: 'Priority dispatch + flight' },
                { item: 'Dehumidifier rental (3 units x 36h)', amount: 720, note: 'Industrial units rapid deploy' },
                { item: 'HVAC motor replacement + labor', amount: 1580, note: 'Emergency maintenance call' },
                { item: 'Manual override labor', amount: 400, note: 'Field team 4h emergency shift' },
            ],
        },
        events: [
            {
                step: 1,
                day: 45,
                title: 'Ventilation System Offline',
                description: 'IoT monitoring detects ventilation fan failure at 10:15. Greenhouse humidity climbing rapidly: 78%  -> 88% in 45 minutes. Temperature rising to 28°C.',
                sensorOverrides: { temp_C: 28.0, humidity_pct: 88, wind_speed_ms: 0.1, leaf_wetness_hrs: 2.0, light_Lux: 6000 },
                pestOverrides: { botrytis_spore_index: 45 },
                expectedAction: null,
                aiAgentActions: [
                    { agent: 'perception', action: 'IoT ALERT: Ventilation fan A2-EXH-01 offline. No heartbeat for 300 seconds.' },
                    { agent: 'watchdog', action: '[ALERT] SYSTEM FAILURE: Greenhouse humidity rising at 2.2%/10min. Emergency protocol initiated.' },
                    { agent: 'perception', action: 'Backup sensor validation: 3/3 humidity sensors confirm rapid climb in A2-Main zone' },
                ],
            },
            {
                step: 2,
                day: 45,
                title: 'Emergency Risk Escalation',
                description: 'Humidity hits 94% within 90 minutes of failure. Botrytis risk surges to 82/100. AI calculates: without ventilation, Grade A flowers at risk within 4 hours.',
                sensorOverrides: { temp_C: 30.2, humidity_pct: 94, wind_speed_ms: 0.0, leaf_wetness_hrs: 3.5 },
                pestOverrides: { botrytis_spore_index: 72 },
                expectedAction: 'risk_trigger',
                aiAgentActions: [
                    { agent: 'analysis', action: 'Humidity trajectory: 94% and climbing. Without fix: 98%+ within 2h. Botrytis risk: 82/100.' },
                    { agent: 'decision', action: 'CRITICAL: System failure + disease risk compound event. Multi-factor emergency Rx needed.' },
                    { agent: 'watchdog', action: 'Maintenance alert dispatched to HVAC team. Backup generator check initiated.' },
                ],
            },
            {
                step: 3,
                day: 45,
                title: 'Emergency Compound Prescription',
                description: 'System generates emergency Rx: (1) Manual door/window override for immediate ventilation, (2) Portable dehumidifier deployment, (3) Carbendazim emergency spray on high-risk zones.',
                sensorOverrides: { temp_C: 31.0, humidity_pct: 96, leaf_wetness_hrs: 4.2 },
                pestOverrides: { botrytis_spore_index: 78 },
                expectedAction: 'prescription_normal',
                aiAgentActions: [
                    { agent: 'decision', action: 'Emergency compound Rx: manual ventilation + dehumidifiers + Carbendazim spray' },
                    { agent: 'decision', action: 'PHI check: Carbendazim 7d PHI vs 8d to harvest  -> PASS (tight margin logged)' },
                    { agent: 'audit', action: 'Pre-audit: emergency protocol flag set. Higher scrutiny on PHI compliance.' },
                ],
                prescriptionData: {
                    primary: { chemical: 'Carbendazim (澶氳弻鐏?', method: 'Emergency spray + manual ventilation', cost: 6200 },
                    measures: [
                        { action: 'Manual door/window override', actor: 'Field Team', priority: 'IMMEDIATE' },
                        { action: 'Portable dehumidifier x3', actor: 'Facility Team', priority: 'HIGH' },
                        { action: 'Carbendazim emergency spray', actor: 'Drone-01', priority: 'HIGH' },
                        { action: 'HVAC repair dispatch', actor: 'Maintenance', priority: 'MEDIUM' },
                    ],
                },
            },
            {
                step: 4,
                day: 45,
                title: 'Emergency Execution  - 4 Actors',
                description: 'Field team opens all doors/windows manually. Portable dehumidifiers deployed. Drone executes Carbendazim spray. HVAC maintenance team dispatched.',
                sensorOverrides: { temp_C: 27.5, humidity_pct: 88, leaf_wetness_hrs: 3.8, wind_speed_ms: 0.8 },
                pestOverrides: { botrytis_spore_index: 70 },
                expectedAction: 'execution',
                aiAgentActions: [
                    { agent: 'execution', action: '4-actor dispatch: Field Team (doors) + Facility (dehumidifiers) + Drone-01 (spray) + HVAC (repair)' },
                    { agent: 'perception', action: 'Humidity responding: 96%  -> 88% within 30min of manual ventilation override' },
                    { agent: 'execution', action: 'Drone spray complete: Carbendazim applied to A2-Main and A2-North zones. Fingerprint: MATCH.' },
                ],
            },
            {
                step: 5,
                day: 46,
                title: 'HVAC Repaired  - System Restored',
                description: 'Ventilation fan motor replaced. System back online at 08:30 Day 46. Humidity normalizing to 78%. Dehumidifiers removed. Drone verification scan scheduled.',
                sensorOverrides: { temp_C: 23.0, humidity_pct: 78, wind_speed_ms: 0.5, leaf_wetness_hrs: 2.0, light_Lux: 9000 },
                pestOverrides: { botrytis_spore_index: 55 },
                expectedAction: null,
                aiAgentActions: [
                    { agent: 'perception', action: 'IoT heartbeat restored: A2-EXH-01 online. Automated ventilation resuming.' },
                    { agent: 'analysis', action: 'Post-intervention: humidity stabilized at 78%. Botrytis risk declining: 55/100.' },
                    { agent: 'watchdog', action: 'System failure incident resolved. Monitoring elevated for 72h precaution.' },
                ],
            },
            {
                step: 6,
                day: 47,
                title: '48h Verification  - Outbreak Prevented',
                description: 'Drone scan confirms: no new Botrytis lesions. Spore index at 32 (declining). All stems Grade A quality maintained. Revenue protected: CNY 72,000.',
                sensorOverrides: { temp_C: 22.0, humidity_pct: 75, wind_speed_ms: 0.4, leaf_wetness_hrs: 1.5, light_Lux: 8500 },
                pestOverrides: { botrytis_spore_index: 32 },
                expectedAction: null,
                aiAgentActions: [
                    { agent: 'perception', action: 'Verification scan: zero new lesions. All 15,000 stems Grade A quality.' },
                    { agent: 'analysis', action: 'Emergency response efficacy: 100%. System failure contained within 18h.' },
                ],
            },
            {
                step: 7,
                day: 48,
                title: 'Final Audit  - Emergency Resolved',
                description: 'Full audit generated. Risk dropped from 82 to 28. Grade A protected. Revenue saved: CNY 72,000. Recommendation: add redundant ventilation fan.',
                sensorOverrides: { temp_C: 22.5, humidity_pct: 73, wind_speed_ms: 0.5, light_Lux: 9000 },
                pestOverrides: { botrytis_spore_index: 28 },
                expectedAction: 'audit',
                aiAgentActions: [
                    { agent: 'audit', action: 'Emergency audit: 82 -> 8 risk. CNY 72,000 protected. Response time: 12 min.' },
                    { agent: 'audit', action: 'Recommendation: install redundant fan (CNY 2,500) to prevent future single-point failures' },
                    { agent: 'analysis', action: 'ML feedback: system failure response model updated. 175 training points captured.' },
                ],
            },
        ],
        expectedOutcome: 'Ventilation failure contained. Grade A preserved through emergency multi-actor response. Revenue protected: ~72,000 yuan.',
    },
};

export const getScenarioList = () => Object.values(SCENARIOS).map(s => ({
    id: s.id,
    name: s.name,
    nameZh: s.nameZh,
    description: s.description,
    field: s.field,
    crop: s.crop,
    riskLevel: s.riskLevel,
    eventCount: s.events.length,
    expectedOutcome: s.expectedOutcome,
    daysToHarvest: s.daysToHarvest,
    startDay: s.startDay,
    complexity: s.complexity,
    threatType: s.threatType,
    primaryThreat: s.primaryThreat,
    outcomeMetrics: s.outcomeMetrics,
    aiAgents: s.aiAgents,
}));

