import React from 'react';
import useStore from '../engine/store';
import StatusBadge from '../components/StatusBadge';
import MetricCard from '../components/MetricCard';
import Icon from '../components/Icon';
import { getComplianceSummary, DECISION_LOOP_STAGES } from '../engine/auditEngine';

export default function AuditReport() {
    const { auditRecords, generateAudit, activePrescription, activeExecution, fields, activeFieldId } = useStore();
    const field = fields[activeFieldId];
    const compliance = getComplianceSummary(auditRecords);
    const latestAudit = auditRecords[auditRecords.length - 1];

    return (
        <div className="page">
            <div className="page-header">
                <div>
                    <h1 className="page-title">Audit Report</h1>
                    <p className="page-subtitle">Stage 5: Audit — {field?.name}</p>
                </div>
                <button className="btn btn-primary" onClick={generateAudit} disabled={!activePrescription || !activeExecution} style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
                    Generate Audit <Icon name="chevron-right" size={14} />
                </button>
            </div>

            {/* Decision Loop Visualization */}
            <div className="card" style={{ marginBottom: 16 }}>
                <h3 className="card-title">5-Stage Decision Loop</h3>
                <div className="decision-loop">
                    {DECISION_LOOP_STAGES.map((stage, i) => (
                        <React.Fragment key={stage.id}>
                            <div className="loop-stage">
                                <div className="loop-icon">
                                    <Icon name={stage.icon} size={32} />
                                </div>
                                <div className="loop-name">{stage.name}</div>
                                <div className="loop-desc">{stage.nameZh}</div>
                            </div>
                            {i < DECISION_LOOP_STAGES.length - 1 && (
                                <div className="loop-arrow">
                                    <Icon name="arrow-right" size={16} />
                                </div>
                            )}
                        </React.Fragment>
                    ))}
                </div>
            </div>

            {/* Compliance Summary */}
            <div className="grid grid-3">
                <MetricCard label="Total Audits" value={compliance.total} icon="audit" />
                <MetricCard label="Compliance Rate" value={`${compliance.rate}% `} status={compliance.rate === 100 ? 'low' : 'elevated'} icon="check" />
                <MetricCard label="Compliant Records" value={compliance.compliant} unit={`/ ${compliance.total} `} status="low" />
            </div>

            {/* Compliance Badges */}
            {auditRecords.length > 0 && (
                <div className="card" style={{ marginTop: 16 }}>
                    <h3 className="card-title">Compliance Badges</h3>
                    <div style={{ display: 'flex', flexWrap: 'wrap', gap: 12 }}>
                        {[
                            { key: 'phi', label: 'PHI Compliant' },
                            { key: 'gap', label: 'G.A.P.' },
                            { key: 'fsma204', label: 'FSMA 204' },
                            { key: 'label', label: 'Pesticide Label' },
                            { key: 'wind', label: 'Wind Safe' },
                        ].map(b => (
                            <div key={b.key} className="compliance-badge">
                                <StatusBadge status={compliance.badges?.[b.key] ? 'pass' : 'fail'} label={b.label} size="lg" />
                            </div>
                        ))}
                    </div>
                </div>
            )}

            {/* Latest Audit Detail */}
            {latestAudit && (
                <>
                    <div className="card" style={{ marginTop: 16, borderLeft: `3px solid ${latestAudit.fingerprintMatch ? '#10b981' : '#ef4444'} ` }}>
                        <h3 className="card-title">Latest Audit: {latestAudit.id}</h3>

                        {/* Decision Chain */}
                        <div style={{ marginBottom: 16 }}>
                            <div style={{ fontSize: '0.75rem', fontWeight: 600, color: '#94a3b8', marginBottom: 8, textTransform: 'uppercase' }}>Decision Chain</div>
                            <div className="decision-chain">
                                <div className="chain-step">
                                    <span className="chain-label">Generated by</span>
                                    <span className="chain-value">{latestAudit.decisionChain.generatedBy}</span>
                                </div>
                                <div className="chain-arrow"><Icon name="arrow-right" size={14} /></div>
                                <div className="chain-step">
                                    <span className="chain-label">Approved by</span>
                                    <span className="chain-value">{latestAudit.decisionChain.approvedBy}</span>
                                </div>
                                <div className="chain-arrow"><Icon name="arrow-right" size={14} /></div>
                                <div className="chain-step">
                                    <span className="chain-label">Executed by</span>
                                    <span className="chain-value">{latestAudit.decisionChain.executedBy}</span>
                                </div>
                            </div>
                        </div>

                        {/* Responsibility */}
                        <div style={{ marginBottom: 16, padding: 12, background: '#111827', borderRadius: 8 }}>
                            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 6 }}>
                                <span style={{ fontSize: '0.75rem', fontWeight: 600, color: '#94a3b8', textTransform: 'uppercase' }}>Responsibility Assignment</span>
                                <StatusBadge status={latestAudit.responsibilityAssignment} />
                            </div>
                            <div style={{ fontSize: '0.8rem', color: '#e2e8f0' }}>{latestAudit.responsibilityNote}</div>
                        </div>

                        {/* Fingerprint */}
                        <div style={{ marginBottom: 16, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                            <span style={{ fontSize: '0.8rem', color: '#94a3b8' }}>Execution Fingerprint</span>
                            <StatusBadge status={latestAudit.fingerprintMatch ? 'match' : 'mismatch'} />
                        </div>

                        {/* Before / After */}
                        <div className="grid grid-2" style={{ gap: 12, marginBottom: 16 }}>
                            <div style={{ padding: 12, background: '#111827', borderRadius: 8, borderLeft: '3px solid #ef4444' }}>
                                <div style={{ fontSize: '0.7rem', color: '#94a3b8', textTransform: 'uppercase', marginBottom: 4 }}>Before</div>
                                <div style={{ fontSize: '1.2rem', fontWeight: 700, color: '#ef4444' }}>{latestAudit.beforeState.riskScore}/100</div>
                                <div style={{ fontSize: '0.75rem', color: '#94a3b8' }}>Grade {latestAudit.beforeState.gradeClass} | ¥{latestAudit.beforeState.revenueAtRisk.toLocaleString()} at risk</div>
                            </div>
                            <div style={{ padding: 12, background: '#111827', borderRadius: 8, borderLeft: '3px solid #10b981' }}>
                                <div style={{ fontSize: '0.7rem', color: '#94a3b8', textTransform: 'uppercase', marginBottom: 4 }}>After</div>
                                <div style={{ fontSize: '1.2rem', fontWeight: 700, color: '#10b981' }}>{latestAudit.afterState.riskScore}/100</div>
                                <div style={{ fontSize: '0.75rem', color: '#94a3b8' }}>Grade {latestAudit.afterState.gradeClass} | ¥{latestAudit.afterState.revenueAtRisk.toLocaleString()} at risk</div>
                            </div>
                        </div>

                        {/* Economic Impact */}
                        <div style={{ padding: 12, background: '#111827', borderRadius: 8 }}>
                            <div style={{ fontSize: '0.75rem', fontWeight: 600, color: '#94a3b8', textTransform: 'uppercase', marginBottom: 8 }}>Economic Impact</div>
                            <div className="grid grid-3" style={{ gap: 8 }}>
                                <MetricCard label="Revenue Protected" value={`¥${latestAudit.economicImpact.revenueProtected.toLocaleString()} `} status="low" />
                                <MetricCard label="Cost of Action" value={`¥${latestAudit.economicImpact.costOfAction.toLocaleString()} `} />
                                <MetricCard label="ROI" value={`${latestAudit.economicImpact.roi} x`} status={latestAudit.economicImpact.roi > 5 ? 'low' : 'monitoring'} />
                            </div>
                        </div>
                    </div>
                </>
            )}

            {/* No audit */}
            {auditRecords.length === 0 && (
                <div className="card" style={{ textAlign: 'center', padding: 40, marginTop: 16 }}>
                    <div style={{ display: 'flex', justifyContent: 'center', color: 'var(--text-muted)', marginBottom: 8 }}><Icon name="audit" size={48} /></div>
                    <div style={{ color: '#94a3b8' }}>No audit records yet. Complete the prescription-execution cycle to generate an audit.</div>
                </div>
            )}

            {/* Previous Audits */}
            {auditRecords.length > 1 && (
                <div className="card" style={{ marginTop: 16 }}>
                    <h3 className="card-title">Audit History</h3>
                    <table className="data-table">
                        <thead><tr><th>AUD ID</th><th>Rx</th><th>Fingerprint</th><th>Responsibility</th><th>Revenue Protected</th><th>Status</th></tr></thead>
                        <tbody>
                            {auditRecords.slice(0, -1).reverse().map(a => (
                                <tr key={a.id}>
                                    <td>{a.id}</td>
                                    <td>{a.prescriptionId}</td>
                                    <td><StatusBadge status={a.fingerprintMatch ? 'match' : 'mismatch'} /></td>
                                    <td><StatusBadge status={a.responsibilityAssignment} /></td>
                                    <td style={{ fontFamily: 'monospace' }}>¥{a.economicImpact.revenueProtected.toLocaleString()}</td>
                                    <td><StatusBadge status={a.status === 'verified' ? 'pass' : 'fail'} label={a.status} /></td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            )}
        </div>
    );
}
